### ISSUE TITLE
Tests fail with spark 1.6rc

### ISSUE THREAD

**Issue by skonto** [typesafehub/mesos-spark-integration-tests#37]
https://ci.typesafe.com/job/spark-mesos-integration-tests-docker-nightly/27/

**Comment by skonto** [comment]
We need to increase the memory to .set("spark.executor.memory", "512mb")
in MestsIntTestHelper.

Another bug is not on our side:
https://issues.apache.org/jira/browse/SPARK-12345
https://github.com/apache/spark/pull/8669#issuecomment-165026987

**Comment by dragos** [comment]
See #38

**Comment by skonto** [comment]
Right now our tests in cluster mode pass in 1.5.2, master(2.0.0) and fail in 1.6.0.-rc3
check comments in #39 ...

**Comment by skonto** [comment]
There reason it works now in 2.0.0 is that since we pass the env var with value:
(SPARK_EXECUTOR_URI,/var/spark/spark-2.0.0-SNAPSHOT-bin-test.tgz)
the code in MesosClusterScheduler will evaluate a non null value for executorUri:
 val executorUri = desc.schedulerProperties.get("spark.executor.uri")
      .orElse(desc.command.environment.get("SPARK_EXECUTOR_URI"))
Later on the follwing line is run:
https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosClusterScheduler.scala#L385

The env is clean no SPARK_HOME only SPARK_EXECUTOR_URI is passed remotely.
So spark-submit will pick as SPARK_HOME the path from which it was called in the first place.

btw in our tests log i saw when spark context is stopped in 2.0.0:
15/12/21 22:43:37 INFO SparkContext: Successfully stopped SparkContext
15/12/21 22:43:37 WARN Dispatcher: Message RemoteProcessDisconnected(192.168.2.7:60345) dropped.
java.lang.IllegalStateException: RpcEnv already stopped.
	at org.apache.spark.rpc.netty.Dispatcher.postMessage(Dispatcher.scala:159)
	at org.apache.spark.rpc.netty.Dispatcher.postToAll(Dispatcher.scala:109)
	at org.apache.spark.rpc.netty.NettyRpcHandler.channelInactive(NettyRpcEnv.scala:621)
	at org.apache.spark.network.server.TransportRequestHandler.channelInactive(TransportRequestHandler.java:99)
	at org.apache.spark.network.server.TransportChannelHandler.channelInactive(TransportChannelHandler.java:104)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:257)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at org.apache.spark.network.util.TransportFrameDecoder.channelInactive(TransportFrameDecoder.java:183)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:828)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:621)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:328)
	at io.netty.util.concurrent.SingleThreadEventExecutor.confirmShutdown(SingleThreadEventExecutor.java:627)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:362)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at java.lang.Thread.run(Thread.java:745)

**Comment by dragos** [comment]
Would https://github.com/typesafehub/mesos-spark-integration-tests/pull/38 help here (using `--conf` instead of environment variables)?

**Comment by skonto** [comment]
now tests run with v1.6 https://ci.typesafe.com/job/spark-mesos-integration-tests-docker-nightly/59/ i will close this for now.
