### ISSUE TITLE
suite is broken MultiClusterModeRunner assumes zk

### ISSUE THREAD

**Issue by skonto** [typesafehub/mesos-spark-integration-tests#61]
MultiClusterModeRunner.run(args) shouldnt be there in MesosIntegrationTestRunner by default because we dont run tests with zk by default. I would like to keep it that way we are testing two different things... also run-tests.sh does not use zk by default. Please comply with that. @tnachen  Thats why as i said earlier we have a different project running tests with zk.... 
It seems that the last commit after LGTM changed the logic. I expected a different sbt task for those tests not integrated to the rest, this is what i reviewed.

Killing framework eb6b1246-bb25-452c-b904-50f1a5d4ebb2-0007

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    53    0     0  100    53      0  27361 --:--:-- --:--:-- --:--:-- 53000
[error] (run-main-0) com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'spark.zk'
com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'spark.zk'
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:147)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:206)
	at com.typesafe.spark.test.mesos.framework.runners.MultiClusterModeRunner$.run(MultiClusterModeRunner.scala:43)
	at com.typesafe.spark.test.mesos.framework.runners.MesosIntegrationTestRunner$.main(MesosIntegrationTestRunner.scala:14)
	at com.typesafe.spark.test.mesos.framework.runners.MesosIntegrationTestRunner.main(MesosIntegrationTestRunner.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
[trace] Stack trace suppressed: run last *:runMain for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)

**Comment by tnachen** [comment]
@skonto sorry I thought zk is enabled by default with docker build, I changed it after @mgummelt commented on having just one runner. I can put it back where I had before.

**Comment by mgummelt** [comment]
Ah yea I was the one that suggested merging them.  I still would prefer to have a single test runner, just with a `--zk` flag or `--multiple-dispatchers` or something.  Then we only have a single, configurable entrypoint to run all the tests.

**Comment by skonto** [comment]
you can add it but make sure it runs locally by detecting if zk is there or something.... as the rest of the tests run with or without zk....

**Comment by tnachen** [comment]
#63 is attempting to fix this

**Comment by skonto** [comment]
fixed
